name: Sync Upstream

permissions: write-all

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Sync Upstream
        uses: zhangnew/sync-upstream@v1
        with:
          upstream: uwzis/GPU-Passthrough-Manager
          upstream-branch: master
          branch: upstream
